project:
  groups:
    - group: App
      files:
        - file: app/main.c
        - file: app/gcc_M55_HE.ld
          for-context: +HE
        - file: app/gcc_M55_HP.ld
          for-context: +HP
  components:
    # needed for Alif Ensemble support
    - component: AlifSemiconductor::Device:Startup&C Startup@0.9.0
    - component: ARM::CMSIS:CORE@5.6.0
    
    # peripheral drivers & middleware, uncomment as needed
    # - component: AlifSemiconductor::Device:SOC Peripherals:ADC@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:Analog Config@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:CAMERA Controller@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:CDC200@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:CRC@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:Comparator@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:DAC@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:DMA@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:Ethernet MAC@1.0.0
    - component: AlifSemiconductor::Device:SOC Peripherals:GPIO@0.9.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:HWSEM@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:I2S@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:I3C@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:LPTIMER@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:MIPI CSI2@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:MIPI DSI@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:MRAM Flash@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:OSPI Controller@1.0.0
    - component: AlifSemiconductor::Device:SOC Peripherals:PINCONF@0.9.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:RTC@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:SPI@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:USART@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:UTIMER@1.0.0
    # - component: AlifSemiconductor::Device:SOC Peripherals:WDT@1.0.0
    
    # - component: AlifSemiconductor::Device:OSPI XIP:core@1.0.0
    # - component: AlifSemiconductor::Device:OSPI XIP:utility@1.0.0
    # - component: AlifSemiconductor::Device:SE Services:MHU Driver@0.63.0
    # - component: AlifSemiconductor::Device:SE Services:SE RunTime services&Lib@0.63.0
    # - component: AlifSemiconductor::Device:SE Services:SE RunTime services&Source@0.63.0

    # - component: AlifSemiconductor::BSP:External peripherals:CAMERA Sensor MT9M114@1.0.0
    # - component: AlifSemiconductor::BSP:External peripherals:CAMERA Sensor ARX3A0@1.0.0
    # - component: AlifSemiconductor::BSP:External peripherals:Ethernet PHY@1.0.0
    # - component: AlifSemiconductor::BSP:External peripherals:GT911 Touch Controller@1.0.0
    # - component: AlifSemiconductor::BSP:External peripherals:ILI9806E LCD panel@1.0.0
    # - component: AlifSemiconductor::BSP:External peripherals:OSPI Flash ISSI@1.0.0

    # - component: AlifSemiconductor::FreeRTOS:FreeRTOS+ TCP:Network Interface&Ensemble@2.3.2

    # - component: AlifSemiconductor::RTOS&AzureRTOS:FILEX:Core@6.1.8
    # - component: AlifSemiconductor::RTOS&AzureRTOS:FILEX:SD Driver@1.0.0
    # - component: AlifSemiconductor::RTOS&AzureRTOS:Kernel@6.1.3
    # - component: AlifSemiconductor::RTOS&AzureRTOS:Netx Duo:Core@6.1.7
    # - component: AlifSemiconductor::RTOS&AzureRTOS:Netx Duo:Ethernet Driver@1.0.0
    # - component: AlifSemiconductor::RTOS&AzureRTOS:Netx Duo:IoT@1.0.0
    # - component: AlifSemiconductor::RTOS&AzureRTOS:USBX:CDC Device Class@6.1.8
    # - component: AlifSemiconductor::RTOS&AzureRTOS:USBX:Core@6.1.8
    # - component: AlifSemiconductor::RTOS&AzureRTOS:USBX:Device Class Driver@6.1.8
